// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:moustache_ping/features/speed_test/speed_result.dart';
import 'package:moustache_ping/features/subnet_scan/scan_snapshot.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ScanSnapshotAdapter());
    registerAdapter(SpeedResultAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ScanSnapshotAdapter());
    registerAdapter(SpeedResultAdapter());
  }
}
